sudo: required
language: node_js
services:
  - docker

before_install:

script:

after_success:
  - docker build -t auth-service ./dockerfiles/auth.Dockerfile
  - docker build -t router-service ./dockerfiles/router.Dockerfile
  - docker build -t sms-service ./dockerfiles/sms.Dockerfile
  - docker build -t redis-server ./dockerfiles/redis.Dockerfile

  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push jrblando/authentication-service:auth-service
  - docker push jrblando/authentication-service:router-service
  - docker push jrblando/authentication-service:sms-service
  - docker push jrblando/authentication-service:redis-server
