sudo: required
language: node_js
services:
  - docker
  - git
branches:
  only:
  - master
  - staging
  - develop

before_install:

script:
  - cp -a ./config/. ./env/

after_success:
  - docker build -t jrblando/authentication-service:latest -f ./dockerfiles/auth.Dockerfile .
  - docker build -t jrblando/nginx-router:latest -f ./dockerfiles/router.Dockerfile .
  - docker build -t jrblando/vendor-sms-service:latest -f ./dockerfiles/sms.Dockerfile .
  - docker build -t jrblando/custom-redis-server:latest -f ./dockerfiles/redis.Dockerfile .

  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push jrblando/authentication-service:latest
  - docker push jrblando/nginx-router:latest
  - docker push jrblando/vendor-sms-service:latest
  - docker push jrblando/custom-redis-server:latest

  - rm -r ./env
  - git rm -r ./config
  - git commit -m "remove config"
  - git push https://"$GIT_USER":"$GIT_PASSWORD"@github.com/onmondo/authentication-service.git develop
  - [ci skip]
