version: '3'
services:
  route-server:
    restart: always
    build: 
      context: .
      dockerfile: ./dockerfiles/router.Dockerfile
    ports:
      - '3004:80'
  # redis-server:
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/redis.Dockerfile
  redis-server:
    build:
      context: .
      dockerfile: ./dockerfiles/redis.local.Dockerfile
  mongodb-server:
    build:
      context: .
      dockerfile: ./dockerfiles/mongodb.local.Dockerfile
  auth-service:
    build: 
      context: .
      dockerfile: ./dockerfiles/auth.Dockerfile
  # auth-staging-service:
  #   build: 
  #     context: .
  #     dockerfile: ./dockerfiles/auth.staging.Dockerfile    
  # auth-test-service:
  #   build: 
  #     context: .
  #     dockerfile: ./dockerfiles/auth.test.Dockerfile
  sms-service:
    build: 
      context: .
      dockerfile: ./dockerfiles/sms.Dockerfile
  users-service:
    build: 
      context: .
      dockerfile: ./dockerfiles/users.Dockerfile
    depends_on:
      - mongodb-server